local M = {}

function M.setup(c)
  return {
    ["@variable"] = { fg = c.fg_bright },
    ["@variable.builtin"] = { fg = c.purple },
    ["@variable.parameter"] = { fg = c.fg_bright },
    ["@variable.member"] = { fg = c.fg_bright },
    ["@constant"] = { fg = c.cyan },
    ["@constant.builtin"] = { fg = c.cyan },
    ["@constant.macro"] = { fg = c.cyan },
    ["@module"] = { fg = c.purple_light },
    ["@string"] = { fg = c.green_olive },
    ["@string.escape"] = { fg = c.green_olive },
    ["@string.regexp"] = { fg = c.cyan },
    ["@character"] = { fg = c.green_olive },
    ["@number"] = { fg = c.cyan },
    ["@boolean"] = { fg = c.cyan },
    ["@float"] = { fg = c.cyan },
    ["@function"] = { fg = c.green_lime },
    ["@function.builtin"] = { fg = c.purple },
    ["@function.call"] = { fg = c.green_lime },
    ["@function.macro"] = { fg = c.green_lime },
    ["@function.method"] = { fg = c.green_lime },
    ["@function.method.call"] = { fg = c.green_lime },
    ["@constructor"] = { fg = c.purple },
    ["@operator"] = { fg = c.green_light },
    ["@keyword"] = { fg = c.purple },
    ["@keyword.function"] = { fg = c.purple },
    ["@keyword.operator"] = { fg = c.green_light },
    ["@keyword.import"] = { fg = c.purple },
    ["@keyword.return"] = { fg = c.purple },
    ["@keyword.exception"] = { fg = c.purple },
    ["@keyword.conditional"] = { fg = c.purple },
    ["@keyword.repeat"] = { fg = c.purple },
    ["@keyword.storage"] = { fg = c.purple },
    ["@keyword.directive"] = { fg = c.purple },
    ["@punctuation.bracket"] = { fg = c.punctuation },
    ["@punctuation.delimiter"] = { fg = c.punctuation },
    ["@punctuation.special"] = { fg = c.cyan },
    ["@comment"] = { fg = c.comment, italic = true },
    ["@type"] = { fg = c.cyan },
    ["@type.builtin"] = { fg = c.purple },
    ["@type.definition"] = { fg = c.cyan },
    ["@type.qualifier"] = { fg = c.purple },
    ["@attribute"] = { fg = c.purple_light },
    ["@property"] = { fg = c.fg_bright },
    ["@tag"] = { fg = c.purple },
    ["@tag.attribute"] = { fg = c.purple_light },
    ["@tag.delimiter"] = { fg = c.punctuation },
    ["@markup.heading"] = { fg = c.green_light, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.raw"] = { fg = c.punctuation },
    ["@markup.link"] = { fg = c.green_light },
    ["@markup.link.url"] = { fg = c.green_olive, underline = true },
    ["@markup.link.label"] = { fg = c.green_light },
    ["@markup.list"] = { fg = c.green_light },
  }
end

return M
